version: 1
update_configs:
  - package_manager: "python"
    directory: "/"
    update_schedule: "monthly"
    default_reviewers:
      - "underyx"
    default_assignees:
      - "underyx"
  - package_manager: "docker"
    directory: "/"
    update_schedule: "monthly"
    default_reviewers:
      - "underyx"
    default_assignees:
      - "underyx"
